# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grove < Formula
  desc "Git worktree manager that handles the setup work"
  homepage "https://github.com/verbaux/grove"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/verbaux/grove/releases/download/v0.1.0/grove_0.1.0_darwin_amd64.tar.gz"
      sha256 "f744ba548b0f1afa53cb3ac54299bc4bd64bb5b081e96ed4b15caef6ce91cf46"

      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/verbaux/grove/releases/download/v0.1.0/grove_0.1.0_darwin_arm64.tar.gz"
      sha256 "43ee0edfae38f7cda7b779518c9f44c6e61b792300b350650e97499c1f899e6e"

      define_method(:install) do
        bin.install "grove"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/verbaux/grove/releases/download/v0.1.0/grove_0.1.0_linux_amd64.tar.gz"
      sha256 "e23ba901a087b4f25e0b4dd9331891d36d5f8159257272ddd5ec156cb6433ac6"
      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/verbaux/grove/releases/download/v0.1.0/grove_0.1.0_linux_arm64.tar.gz"
      sha256 "2b60546c9c763a99f4a9a2c8895fad96ce79f7bee5c02853694f311ee71b5b25"
      define_method(:install) do
        bin.install "grove"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/grove --version")
  end
end
