# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grove < Formula
  desc "Git worktree manager that handles the setup work"
  homepage "https://github.com/verbaux/grove"
  version "0.7.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/verbaux/grove/releases/download/v0.7.2/grove_0.7.2_darwin_amd64.tar.gz"
      sha256 "830781f88d39a3b392ef1173ffb1bac20ed7684b044ee28100ee800d2f74d5b5"

      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/verbaux/grove/releases/download/v0.7.2/grove_0.7.2_darwin_arm64.tar.gz"
      sha256 "c1700f93e35e0397c752e8e1bb8b6ee6ae83f91d35223ccd9f6405afc5915564"

      define_method(:install) do
        bin.install "grove"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/verbaux/grove/releases/download/v0.7.2/grove_0.7.2_linux_amd64.tar.gz"
      sha256 "153dc36ac828bc9f4c8958b27881404f119cdc330b85f5d9724a93ebb9655eb9"
      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/verbaux/grove/releases/download/v0.7.2/grove_0.7.2_linux_arm64.tar.gz"
      sha256 "0fc05c006eab31bf40d6b5b59badff4cafa794a78181808df6df843a83a1b0ba"
      define_method(:install) do
        bin.install "grove"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/grove --version")
  end
end
